// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/scheduler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Worker -> Coordinator
type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_Registration
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_TaskAck
	//	*WorkerMessage_TaskStatus
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetRegistration() *WorkerRegistration {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *WorkerHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskAck() *TaskAcknowledgement {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_TaskAck); ok {
			return x.TaskAck
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskStatus() *TaskStatus {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_TaskStatus); ok {
			return x.TaskStatus
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_Registration struct {
	Registration *WorkerRegistration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *WorkerHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_TaskAck struct {
	TaskAck *TaskAcknowledgement `protobuf:"bytes,3,opt,name=task_ack,json=taskAck,proto3,oneof"`
}

type WorkerMessage_TaskStatus struct {
	TaskStatus *TaskStatus `protobuf:"bytes,4,opt,name=task_status,json=taskStatus,proto3,oneof"`
}

func (*WorkerMessage_Registration) isWorkerMessage_Payload() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Payload() {}

func (*WorkerMessage_TaskAck) isWorkerMessage_Payload() {}

func (*WorkerMessage_TaskStatus) isWorkerMessage_Payload() {}

// Coordinator -> Worker
type CoordinatorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CoordinatorMessage_WorkerAck
	//	*CoordinatorMessage_TaskStatus
	//	*CoordinatorMessage_TaskAssignment
	Payload       isCoordinatorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinatorMessage) GetPayload() isCoordinatorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CoordinatorMessage) GetWorkerAck() *WorkerAcknowledgement {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_WorkerAck); ok {
			return x.WorkerAck
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetTaskStatus() *TaskStatus {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_TaskStatus); ok {
			return x.TaskStatus
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetTaskAssignment() *TaskAssignment {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_TaskAssignment); ok {
			return x.TaskAssignment
		}
	}
	return nil
}

type isCoordinatorMessage_Payload interface {
	isCoordinatorMessage_Payload()
}

type CoordinatorMessage_WorkerAck struct {
	WorkerAck *WorkerAcknowledgement `protobuf:"bytes,1,opt,name=worker_ack,json=workerAck,proto3,oneof"`
}

type CoordinatorMessage_TaskStatus struct {
	TaskStatus *TaskStatus `protobuf:"bytes,2,opt,name=task_status,json=taskStatus,proto3,oneof"`
}

type CoordinatorMessage_TaskAssignment struct {
	TaskAssignment *TaskAssignment `protobuf:"bytes,3,opt,name=task_assignment,json=taskAssignment,proto3,oneof"`
}

func (*CoordinatorMessage_WorkerAck) isCoordinatorMessage_Payload() {}

func (*CoordinatorMessage_TaskStatus) isCoordinatorMessage_Payload() {}

func (*CoordinatorMessage_TaskAssignment) isCoordinatorMessage_Payload() {}

// WorkerMessage.registration
type WorkerRegistration struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkerId           string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	MaxConcurrentTasks int32                  `protobuf:"varint,2,opt,name=max_concurrent_tasks,json=maxConcurrentTasks,proto3" json:"max_concurrent_tasks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkerRegistration) Reset() {
	*x = WorkerRegistration{}
	mi := &file_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRegistration) ProtoMessage() {}

func (x *WorkerRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRegistration.ProtoReflect.Descriptor instead.
func (*WorkerRegistration) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerRegistration) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerRegistration) GetMaxConcurrentTasks() int32 {
	if x != nil {
		return x.MaxConcurrentTasks
	}
	return 0
}

// WorkerMessage.heartbeat
type WorkerHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemUsage      float64                `protobuf:"fixed64,3,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	ActiveTasks   int32                  `protobuf:"varint,4,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHeartbeat) Reset() {
	*x = WorkerHeartbeat{}
	mi := &file_proto_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHeartbeat) ProtoMessage() {}

func (x *WorkerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHeartbeat.ProtoReflect.Descriptor instead.
func (*WorkerHeartbeat) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerHeartbeat) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerHeartbeat) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *WorkerHeartbeat) GetMemUsage() float64 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

func (x *WorkerHeartbeat) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *WorkerHeartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// WorkerMessage.task_ack (also CoordinatorService.SubmitTask response)
type TaskAcknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAcknowledgement) Reset() {
	*x = TaskAcknowledgement{}
	mi := &file_proto_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAcknowledgement) ProtoMessage() {}

func (x *TaskAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAcknowledgement.ProtoReflect.Descriptor instead.
func (*TaskAcknowledgement) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *TaskAcknowledgement) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAcknowledgement) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// WorkerMessage.task_status (also CoordinatorService.GetTaskStatus response)
type TaskStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId           string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ResultData         string                 `protobuf:"bytes,4,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedTimestamp   int64                  `protobuf:"varint,6,opt,name=started_timestamp,json=startedTimestamp,proto3" json:"started_timestamp,omitempty"`
	CompletedTimestamp int64                  `protobuf:"varint,7,opt,name=completed_timestamp,json=completedTimestamp,proto3" json:"completed_timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_proto_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *TaskStatus) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatus) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskStatus) GetResultData() string {
	if x != nil {
		return x.ResultData
	}
	return ""
}

func (x *TaskStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskStatus) GetStartedTimestamp() int64 {
	if x != nil {
		return x.StartedTimestamp
	}
	return 0
}

func (x *TaskStatus) GetCompletedTimestamp() int64 {
	if x != nil {
		return x.CompletedTimestamp
	}
	return 0
}

// CoordinatorMessage.worker_ack
type WorkerAcknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Registered    bool                   `protobuf:"varint,2,opt,name=registered,proto3" json:"registered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerAcknowledgement) Reset() {
	*x = WorkerAcknowledgement{}
	mi := &file_proto_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerAcknowledgement) ProtoMessage() {}

func (x *WorkerAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerAcknowledgement.ProtoReflect.Descriptor instead.
func (*WorkerAcknowledgement) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *WorkerAcknowledgement) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerAcknowledgement) GetRegistered() bool {
	if x != nil {
		return x.Registered
	}
	return false
}

// CoordinatorMessage.task_assignment
type TaskAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType      string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	TaskData      string                 `protobuf:"bytes,3,opt,name=task_data,json=taskData,proto3" json:"task_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_proto_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskAssignment) GetTaskData() string {
	if x != nil {
		return x.TaskData
	}
	return ""
}

// Client-facing submit task request
type SubmitTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestPayload string                 `protobuf:"bytes,1,opt,name=request_payload,json=requestPayload,proto3" json:"request_payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitTaskRequest) GetRequestPayload() string {
	if x != nil {
		return x.RequestPayload
	}
	return ""
}

// Client-facing get task status request
type GetTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusRequest) Reset() {
	*x = GetTaskStatusRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusRequest) ProtoMessage() {}

func (x *GetTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_proto_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x15proto/scheduler.proto\x12\tscheduler\"\x92\x02\n" +
	"\rWorkerMessage\x12C\n" +
	"\fregistration\x18\x01 \x01(\v2\x1d.scheduler.WorkerRegistrationH\x00R\fregistration\x12:\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1a.scheduler.WorkerHeartbeatH\x00R\theartbeat\x12;\n" +
	"\btask_ack\x18\x03 \x01(\v2\x1e.scheduler.TaskAcknowledgementH\x00R\ataskAck\x128\n" +
	"\vtask_status\x18\x04 \x01(\v2\x15.scheduler.TaskStatusH\x00R\n" +
	"taskStatusB\t\n" +
	"\apayload\"\xe2\x01\n" +
	"\x12CoordinatorMessage\x12A\n" +
	"\n" +
	"worker_ack\x18\x01 \x01(\v2 .scheduler.WorkerAcknowledgementH\x00R\tworkerAck\x128\n" +
	"\vtask_status\x18\x02 \x01(\v2\x15.scheduler.TaskStatusH\x00R\n" +
	"taskStatus\x12D\n" +
	"\x0ftask_assignment\x18\x03 \x01(\v2\x19.scheduler.TaskAssignmentH\x00R\x0etaskAssignmentB\t\n" +
	"\apayload\"c\n" +
	"\x12WorkerRegistration\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x120\n" +
	"\x14max_concurrent_tasks\x18\x02 \x01(\x05R\x12maxConcurrentTasks\"\xa9\x01\n" +
	"\x0fWorkerHeartbeat\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x01R\bcpuUsage\x12\x1b\n" +
	"\tmem_usage\x18\x03 \x01(\x01R\bmemUsage\x12!\n" +
	"\factive_tasks\x18\x04 \x01(\x05R\vactiveTasks\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"J\n" +
	"\x13TaskAcknowledgement\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\"\xfe\x01\n" +
	"\n" +
	"TaskStatus\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vresult_data\x18\x04 \x01(\tR\n" +
	"resultData\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12+\n" +
	"\x11started_timestamp\x18\x06 \x01(\x03R\x10startedTimestamp\x12/\n" +
	"\x13completed_timestamp\x18\a \x01(\x03R\x12completedTimestamp\"T\n" +
	"\x15WorkerAcknowledgement\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1e\n" +
	"\n" +
	"registered\x18\x02 \x01(\bR\n" +
	"registered\"c\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x1b\n" +
	"\ttask_data\x18\x03 \x01(\tR\btaskData\"<\n" +
	"\x11SubmitTaskRequest\x12'\n" +
	"\x0frequest_payload\x18\x01 \x01(\tR\x0erequestPayload\"/\n" +
	"\x14GetTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId2\xad\x01\n" +
	"\x12CoordinatorService\x12L\n" +
	"\n" +
	"SubmitTask\x12\x1c.scheduler.SubmitTaskRequest\x1a\x1e.scheduler.TaskAcknowledgement\"\x00\x12I\n" +
	"\rGetTaskStatus\x12\x1f.scheduler.GetTaskStatusRequest\x1a\x15.scheduler.TaskStatus\"\x002f\n" +
	"\rWorkerService\x12U\n" +
	"\x14ConnectToCoordinator\x12\x18.scheduler.WorkerMessage\x1a\x1d.scheduler.CoordinatorMessage\"\x00(\x010\x01B)Z'distributed-home-value-forecaster/protob\x06proto3"

var (
	file_proto_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_proto_rawDescData
}

var file_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_scheduler_proto_goTypes = []any{
	(*WorkerMessage)(nil),         // 0: scheduler.WorkerMessage
	(*CoordinatorMessage)(nil),    // 1: scheduler.CoordinatorMessage
	(*WorkerRegistration)(nil),    // 2: scheduler.WorkerRegistration
	(*WorkerHeartbeat)(nil),       // 3: scheduler.WorkerHeartbeat
	(*TaskAcknowledgement)(nil),   // 4: scheduler.TaskAcknowledgement
	(*TaskStatus)(nil),            // 5: scheduler.TaskStatus
	(*WorkerAcknowledgement)(nil), // 6: scheduler.WorkerAcknowledgement
	(*TaskAssignment)(nil),        // 7: scheduler.TaskAssignment
	(*SubmitTaskRequest)(nil),     // 8: scheduler.SubmitTaskRequest
	(*GetTaskStatusRequest)(nil),  // 9: scheduler.GetTaskStatusRequest
}
var file_proto_scheduler_proto_depIdxs = []int32{
	2,  // 0: scheduler.WorkerMessage.registration:type_name -> scheduler.WorkerRegistration
	3,  // 1: scheduler.WorkerMessage.heartbeat:type_name -> scheduler.WorkerHeartbeat
	4,  // 2: scheduler.WorkerMessage.task_ack:type_name -> scheduler.TaskAcknowledgement
	5,  // 3: scheduler.WorkerMessage.task_status:type_name -> scheduler.TaskStatus
	6,  // 4: scheduler.CoordinatorMessage.worker_ack:type_name -> scheduler.WorkerAcknowledgement
	5,  // 5: scheduler.CoordinatorMessage.task_status:type_name -> scheduler.TaskStatus
	7,  // 6: scheduler.CoordinatorMessage.task_assignment:type_name -> scheduler.TaskAssignment
	8,  // 7: scheduler.CoordinatorService.SubmitTask:input_type -> scheduler.SubmitTaskRequest
	9,  // 8: scheduler.CoordinatorService.GetTaskStatus:input_type -> scheduler.GetTaskStatusRequest
	0,  // 9: scheduler.WorkerService.ConnectToCoordinator:input_type -> scheduler.WorkerMessage
	4,  // 10: scheduler.CoordinatorService.SubmitTask:output_type -> scheduler.TaskAcknowledgement
	5,  // 11: scheduler.CoordinatorService.GetTaskStatus:output_type -> scheduler.TaskStatus
	1,  // 12: scheduler.WorkerService.ConnectToCoordinator:output_type -> scheduler.CoordinatorMessage
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_scheduler_proto_init() }
func file_proto_scheduler_proto_init() {
	if File_proto_scheduler_proto != nil {
		return
	}
	file_proto_scheduler_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Registration)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_TaskAck)(nil),
		(*WorkerMessage_TaskStatus)(nil),
	}
	file_proto_scheduler_proto_msgTypes[1].OneofWrappers = []any{
		(*CoordinatorMessage_WorkerAck)(nil),
		(*CoordinatorMessage_TaskStatus)(nil),
		(*CoordinatorMessage_TaskAssignment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_proto_depIdxs,
		MessageInfos:      file_proto_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_proto = out.File
	file_proto_scheduler_proto_goTypes = nil
	file_proto_scheduler_proto_depIdxs = nil
}
